image: node:8

cache:
  paths:
  - node_modules/

client_deploy_to_prod:
  only:
    refs:
      - master
  stage: build
  script:
   - apt-get update && apt-get install sshpass
   - npm install
   - CI=false npm run build
   - sshpass -p $PROD_SERVER_PASS scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r build/* root@185.125.46.189:/var/www/html/

client_deploy_to_dev:
  only:
    refs:
      - dev
  stage: build
  script:
   - apt-get update && apt-get install sshpass
   - npm install
   - CI=false npm run build
   - sshpass -p $DEV_SERVER_PASS scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r build/* root@185.125.46.157:/var/www/html/
